### PR TITLE
fix: Server-side rendering

### LINKED ISSUE #371: SSR feature is broken since 3.6.1
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 3.6.1 or 4.0.0

### Description

SSR feature is broken since 3.6.1, you can test with the provided fastify-ssr example

### How to reproduce

Clone the project, go to examples/fastify-ssr, set graphql-hooks to different versions in package.json.

Set graphql-hooks to 3.6.1 or 4.0.0 in package.json
```
"graphql-hooks": "3.6.1",
```
Install, build and start the app, view page source.
```
<script type="text/javascript">
  window.__INITIAL_STATE__={};  
</script>
```
You can see the __INITIAL_STATE__ is empty. SSR is not working.

Now set graphql-hooks to 3.6.0 in package.json
```
"graphql-hooks": "3.6.0",
```
Install, build and start the app agian, view page source.
```
<script type="text/javascript">
  window.__INITIAL_STATE__={"bhilef":{"error":false,"data":{"users":[{"name":"Brian"},{"name":"Jack"},{"name":"Joe"}]}},"ej6ucw":{"error":false,"data":{"hello":"Hello Brian"}}};  
</script>
```
__INITIAL_STATE__ is not empty. SSR is working.

### Suggested solution (optional)
It seems to be related to this line
https://github.com/nearform/graphql-hooks/pull/298/files#diff-dd568ddecea113b2a4d3db093d410fa2R18
in the PR https://github.com/nearform/graphql-hooks/pull/298
the added condition of `!state.loading` is preventing SSR data fetching.

### PR DESCRIPTION
**Pull request by bmullan91**
### What does this PR do?
- fixes #371 
- Updates `clean` command to also clear out build folders - useful for debugging
- Updates `postinstall` to run the build command in each package - required for testing

### Related issues
#371 

### Checklist

- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md)
- [x] I have added or updated any relevant documentation
- [x] I have added or updated any relevant tests

### CODE REVIEW

File: packages/graphql-hooks/src/useClientRequest.js [hunk 1]
```diff
@@ -158,6 +158,15 @@ function useClientRequest(query, initialOpts = {}) {
         if (revisedOpts.useCache) {
           actionResult.useCache = true
           actionResult.cacheKey = revisedCacheKey
+
+          if (client.ssrMode) {
+            const cacheValue = {
+              data: revisedOpts.updateData
+                ? revisedOpts.updateData(state.data, actionResult.data)
```
Comment (Raincal) [inline packages/graphql-hooks/src/useClientRequest.js]: SSR still doesn't work when options.updateData is passed because `state.data` is undefined here.

[Edit with-graphql-hooks](https://codesandbox.io/s/with-graphql-hooks-nfgxb?fontsize=14)

Comment (bmullan91) [reply packages/graphql-hooks/src/useClientRequest.js]: @Raincal If you're up for it we'd welcome a PR - ideally with a breaking test commit that highlights the issue, then the fix :)
