### PR TITLE
Integration tests & bug fixes

### LINKED ISSUE #60: useQuery only resends the query if options.variables change
### Environment

- `graphql-hooks` version: `3.1.0`
- `react` version: `16.8.3`
- Browser:

### Description

The when calling `useQuery(query, options)` with different options for example `operationName` or `fetchOptions` it does not re-send the query.

### How to reproduce

```jsx
const QUERY = `
  query Operation1 {
    hello
  }

  query Operation2 {
    goodbye
  }
`

// example component that might change operationName based on prop
function MyComponent({ operationName }) {
  const { loading, error, data } = useQuery(QUERY, { options: { operationName } })
}
```

### Suggested solution (optional)

```js
// current
React.useEffect(() => {
    queryReq();
  }, [query, JSON.stringify(opts.variables)]);

// fix
React.useEffect(() => {
    queryReq();
  }, [query, JSON.stringify(opts)]);
```

### PR DESCRIPTION
**Pull request by bmullan91**
### What does this PR do?

Fixes bugs (listed below) and also introduces integration tests.

### Related issues

- Fixes #60, #37 

### Checklist

- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md)
- [x] I have added or updated any relevant documentation
- [x] I have added or updated any relevant tests

### CODE REVIEW

File: src/useQuery.js [hunk 1]
```diff
@@ -26,7 +26,7 @@ module.exports = function useQuery(query, opts = {}) {
 
   React.useEffect(() => {
     queryReq();
-  }, [query, JSON.stringify(opts.variables)]);
+  }, [query, JSON.stringify(opts)]);
```
Comment (bmullan91) [inline src/useQuery.js]: We could be more selective of the options to resend a query.. for example _should_ we resend the query if `useCache` or `skipCache` changes?

File: test/integration/useQuery.test.js [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+
+  it('should reset state when options.variables change', async () => {
+    const client = new GraphQLClient({
+      url: '/graphql'
+    });
+
+    // stub the request
+    client.request = () => Promise.resolve({ data: 'data v1' });
+
+    const wrapper = getWrapper(client);
```
Comment (jackdclark) [inline test/integration/useQuery.test.js]: We could move this setup into a beforeEach as it's the same for the other test (& perhaps subsequent tests)

```javascript
let client, wrapper

describe('useQuery Integrations', () => {

  beforeEach(() => {
    client = new GraphQLClient({ url: '/graphql' })
    client.request = () => Promise.resolve({ data: 'data v1' });
    wrapper = getWrapper(client)
  })
```

File: src/useQuery.js (hunk 1 above)
Comment (Joezo) [reply src/useQuery.js]: Should we pass `allOpts` in here? It would be more correct right? As query and allOpts are what are passed to `useClientRequest`.

File: test/integration/useQuery.test.js [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+    expect(() => getByTestId('loading')).toThrow();
+  });
+
+  it('should reset state when options.variables change', async () => {
+    const client = new GraphQLClient({
+      url: '/graphql'
+    });
+
+    // stub the request
+    client.request = () => Promise.resolve({ data: 'data v1' });
```
Comment (jackdclark) [inline test/integration/useQuery.test.js]: minor: This could be a jest mock function. 

```javascript
client.request = jest.fn().mockResolveValue({ data: 'data v1 '})
```
Not essential, it just gives us a nice util to change the resolved value without needing to reassign

```javascript
client.request.mockResolveValueOnce({ data: 'data v2' })
```

File: test/integration/useQuery.test.js [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+  return (
+    <div>
+      {loading && <div data-testid="loading">Loading...</div>}
+      {error && <div data-testid="error">Error</div>}
+      {data && <div data-testid="data">{data}</div>}
+    </div>
+  );
+};
+
+describe('useQuery Integrations', () => {
```
Comment (jackdclark) [inline test/integration/useQuery.test.js]: These are great, good to have some coverage at this level 👍

**Comment by bmullan91** [comment]
@all-contributors please add @bmullan91 for test
