### PR TITLE
Don't require fetch polyfill if ssrMode is false

### LINKED ISSUE #620: Fetch polyfill required even when ssr is configured false
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: `4.0.0`

### Description

Currently if the Client is created on the server without a fetch polyfill it results in error. This happens even when `config.ssr` is `false`. This is an issue with universal code as it means that if the same code that runs on the server it will fail even if a graphql request isn't made.

```
if (!config.fetch && !fetch) {
                          ^

ReferenceError: fetch is not defined
```

### How to reproduce

Create Client in NodeJS:

```
const client = new GraphQLClient({
  url: 'https://test/graphql',
  cache: memCache(),
});
```

### Suggested solution (optional)

Only require fetch to be available if `ssr` is enable in the `config` for the client

### PR DESCRIPTION
**Pull request by penx**
### What does this PR do?

Don't throw an error if fetch is not polyfilled and ssrMode is set to false.

### Related issues

Fixes #620

### Checklist

- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md)
- [ ] I have added or updated any relevant documentation N/A
- [x] I have added or updated any relevant tests

### CODE REVIEW

File: packages/graphql-hooks/src/GraphQLClient.js [hunk 1]
```diff
@@ -182,6 +184,9 @@ class GraphQLClient {
   }
 
   request(operation, options = {}) {
+    if (!this.fetch) {
+      throw new Error(FETCH_POLYFILL_ERROR)
```
Comment (penx) [inline packages/graphql-hooks/src/GraphQLClient.js:188]: I plan to add a test for this error being thrown

**Review by simoneb — COMMENTED** [review]
The code overall LGTM, but I can't get the app to work on my android device. Clicking the login button shows a warning at the bottom with an error that's not very telling and then does nothing.

**Review by simoneb — APPROVED** [review]
LGTM
